#!/usr/bin/with-contenv bashio
# Render /data/config.toml from the add-on options + the Mosquitto service
# credentials, then run the server in `serve` mode as a Mosquitto client. State
# lives in /data, which Home Assistant's native backup captures.
set -e

CONFIG_PATH=/data/config.toml

# --- device identity & tuning (add-on options) ---
RECEIVER_ID=$(bashio::config 'receiver_id')
SENSOR_ID=$(bashio::config 'sensor_id')
SENSOR_NAME=$(bashio::config 'sensor_name')
MQTT_USER=$(bashio::config 'mqtt_user')
MQTT_PASS=$(bashio::config 'mqtt_pass')
FIRMWARE=$(bashio::config 'firmware_version')
FULL_DIST=$(bashio::config 'full_dist')
EMPTY_DIST=$(bashio::config 'empty_dist')
RADAR_SKIP=$(bashio::config 'radar_skip')
RADAR_REPEAT=$(bashio::config 'radar_repeat')
PING_INTERVAL=$(bashio::config 'ping_interval_secs')
HISTORY_MAX=$(bashio::config 'history_max_len')
PUMP_OUT_DROP=$(bashio::config 'pump_out_drop_pct')
LOG_LEVEL=$(bashio::config 'log_level')

if bashio::var.is_empty "${RECEIVER_ID}"; then
  bashio::exit.nok "receiver_id is not set. Run the 'learn' or 'observe' onboarding once to recover it, then fill in the add-on options."
fi

# --- broker connection (our own client) ---
# Use the auto-provided Mosquitto service credentials. The DEVICE authenticates
# separately with mqtt_user/mqtt_pass, which you add to Mosquitto's logins (see DOCS).
if ! bashio::services.available "mqtt"; then
  bashio::exit.nok "No MQTT service available. Install and start the official Mosquitto broker add-on."
fi
BROKER_HOST=$(bashio::services mqtt "host")
BROKER_PORT=$(bashio::services mqtt "port")
BROKER_USER=$(bashio::services mqtt "username")
BROKER_PASS=$(bashio::services mqtt "password")

bashio::log.info "Connecting to Mosquitto at ${BROKER_HOST}:${BROKER_PORT} as ${BROKER_USER}"

cat >"${CONFIG_PATH}" <<EOF
# Generated by the Aquilo add-on from its options on each start. Do not hand-edit;
# change the add-on options instead. State persists in /data and survives restarts.
receiver_id = "${RECEIVER_ID}"
sensor_id = "${SENSOR_ID}"
mqtt_user = "${MQTT_USER}"
mqtt_pass = "${MQTT_PASS}"
firmware_version = "${FIRMWARE}"
sensor_name = "${SENSOR_NAME}"

radar_skip = ${RADAR_SKIP}
radar_repeat = ${RADAR_REPEAT}

data_dir = "/data"
ping_interval_secs = ${PING_INTERVAL}
history_max_len = ${HISTORY_MAX}
pump_out_drop_pct = ${PUMP_OUT_DROP}

[calibration]
full_dist = ${FULL_DIST}
empty_dist = ${EMPTY_DIST}

[broker]
host = "${BROKER_HOST}"
port = ${BROKER_PORT}
username = "${BROKER_USER}"
password = "${BROKER_PASS}"
EOF

export RUST_LOG="${LOG_LEVEL},aquilo_server=${LOG_LEVEL},rumqttd::router=warn"

bashio::log.info "Starting aquilo-server (serve)"
exec /usr/bin/aquilo-server serve --config "${CONFIG_PATH}"
